// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjlBv2apvkrmbtc437WLYiUuAVbSf3zeA',
    appId: '1:999354534828:web:2e059b6cc391ea78b5c809',
    messagingSenderId: '999354534828',
    projectId: 'miload-b07a5',
    authDomain: 'miload-b07a5.firebaseapp.com',
    storageBucket: 'miload-b07a5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcSeXrcan36eXw-lREzonA8Du8rIiYnfg',
    appId: '1:999354534828:android:50f46bf3d2323aa7b5c809',
    messagingSenderId: '999354534828',
    projectId: 'miload-b07a5',
    storageBucket: 'miload-b07a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtRWdrX0bZoVByFVPas7bq7mBusYkVHmY',
    appId: '1:999354534828:ios:8474cfd7879ea374b5c809',
    messagingSenderId: '999354534828',
    projectId: 'miload-b07a5',
    storageBucket: 'miload-b07a5.appspot.com',
    iosClientId: '999354534828-snhmcbhp7sgmaghgu9jvp04vb304tes6.apps.googleusercontent.com',
    iosBundleId: 'com.flutter.flutter-miload',
  );
}
